### PR TITLE
replace xrange with six's range

### PR DESCRIPTION
**Pull request by lucasduffey**
python3 deprecates xrange in favor of range

### CODE REVIEW

**Comment by BinyaminSharet** [comment]
@lucasduffey please add the cPickle fix as well to this pull request.

**Comment by lucasduffey** [comment]
so I'm not entirely sure cPickle applies to anyone else which is why I closed it.

I think that was a problem with my computer - still investigating it

**Comment by BinyaminSharet** [comment]
@lucasduffey this is a real issue when using Python3, and I think using six is a good solution.

**Comment by lucasduffey** [comment]
yep you're right - just pushed it

**Pull request merged**
